version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=archie
      - DB_PASSWORD=postgres
      - DB_NAME=spinnerdb
      - DB_PORT=5432

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: archie
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spinnerdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: